[package]
name = "weather"
version = "1.2.1"
edition = "2024"

[dependencies]
chrono = "0.4.39"
reqwest = "0.12.9"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
tokio = { version = "1.42.0", features = ["full"] }
