[package]
name = "weather-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.12.9"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
tokio = { version = "1.42.0", features = ["full"] }
